---
# tasks file for hugo | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and extracting {{ hugo_app }} {{ hugo_version }}
  unarchive:
    src: "{{ hugo_dl_url }}"
    dest: "{{ hugo_bin_path }}"
    extra_opts:
      - hugo
    remote_src: yes
