---
# tasks file for hugo | EL Family

- name: EL Family | Downloading and extracting {{ hugo_app }} {{ hugo_version }}
  ansible.builtin.unarchive:
    src: "{{ hugo_dl_url }}"
    dest: "{{ hugo_bin_path }}"
    extra_opts:
      - hugo
    remote_src: yes
    owner: "{{ hugo_file_owner }}"
    group: "{{ hugo_file_group }}"
    mode: "{{ hugo_file_mode }}"
