---
# tasks file for hugo

- name: "Downloading and extracting {{ hugo_app }} {{ hugo_version }} on Debian based systems."
  unarchive:
    src: "{{ hugo_dl_url }}"
    dest: "{{ hugo_bin_path }}"
    extra_opts:
      - hugo
    remote_src: yes
